# Generated by Django 5.1.3 on 2024-12-03 07:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqs',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
